# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-21 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lesson', models.CharField(max_length=20)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(blank=True, choices=[('m1', '중1'), ('m2', '중2'), ('m3', '중3'), ('h1', '고1'), ('h2', '고2'), ('h3', '고3'), ('df', '없음')], max_length=2)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
                ('academy_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.AcademyGroup')),
                ('school_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.SchoolGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spelling', models.CharField(max_length=100)),
                ('memo', models.TextField(blank=True)),
                ('meaning', models.CharField(max_length=500)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Note')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='textbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Textbook'),
        ),
    ]
